// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DeleteConstraintExampleG1.Models;

public partial class ModuleStudent
{
    public int AssignmentId { get; set; }

    public int ModuleId { get; set; }

    public int StudentId { get; set; }

    public virtual Module Module { get; set; }

    public virtual Student Student { get; set; }
}