// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace HousesittingG1.Models;

public partial class HousesittingContext : DbContext
{
    public HousesittingContext(DbContextOptions<HousesittingContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.BookingId).HasName("PK__Bookings__73951ACDAC183DFB");

            entity.Property(e => e.BookingId).HasColumnName("BookingID");
            entity.Property(e => e.CustId).HasColumnName("CustID");
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.StartDate).HasColumnType("datetime");

            entity.HasOne(d => d.Cust).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.CustId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Customers_Bookings");
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.CustId).HasName("PK__Customer__049E3A89C2F9AC63");

            entity.Property(e => e.CustId).HasColumnName("CustID");
            entity.Property(e => e.ContactNumber)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.EmergencyContact)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.EmergencyNumber)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.PhysicalAddress)
                .IsRequired()
                .HasMaxLength(250);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}