// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BirdWatcherG1.Models;

public partial class BirdWatcherContext : DbContext
{
    public BirdWatcherContext(DbContextOptions<BirdWatcherContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Spotting> Spottings { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Spotting>(entity =>
        {
            entity.HasKey(e => e.SpottingId).HasName("PK__Spotting__194E04C5355084B8");

            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("ImageURL");
            entity.Property(e => e.SpottingDescription)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.TimeSeen)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}