// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HousesittingG2.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public int CustId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public virtual Customer Cust { get; set; }
}