// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HousesittingG2.Models;

public partial class Customer
{
    public int CustId { get; set; }

    public string FullName { get; set; }

    public string ContactNumber { get; set; }

    public string EmergencyContact { get; set; }

    public string EmergencyNumber { get; set; }

    public string PhysicalAddress { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}