CREATE DATABASE Library2G1;

USE Library2G1;

CREATE TABLE Books (
	BookID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	BookTitle NVARCHAR(255) NOT NULL
);

CREATE TABLE Customers (
	CustomerID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	CustomerName NVARCHAR(255) NOT NULL
);

CREATE TABLE Checkouts (
	CheckoutID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	BookID INT NOT NULL,
	CustomerID INT NOT NULL,
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL
	CONSTRAINT FK_Books_Checkouts FOREIGN KEY (BookID) REFERENCES Books(BookID),
	CONSTRAINT FK_Customers_Checkouts FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);