// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryExampleG2.Models;

public partial class Book
{
    public int BookId { get; set; }

    public string Title { get; set; }

    public string Author { get; set; }

    public string Isbn { get; set; }

    public int Edition { get; set; }

    public int Pages { get; set; }

    public virtual ICollection<Loan> Loans { get; set; } = new List<Loan>();
}