// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryExampleG2.Models;

public partial class Patron
{
    public int PatronId { get; set; }

    public string FullName { get; set; }

    public string PhysicalAddress { get; set; }

    public string EmailAddress { get; set; }

    public string PhoneNumber { get; set; }

    public virtual ICollection<Loan> Loans { get; set; } = new List<Loan>();
}