// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Library2G1.Models;

public partial class Checkout
{
    public int CheckoutId { get; set; }

    public int BookId { get; set; }

    public int CustomerId { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public virtual Book Book { get; set; }

    public virtual Customer Customer { get; set; }
}