// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarRentalG2.Models;

public partial class Car
{
    public int CarId { get; set; }

    public string CarMake { get; set; }

    public string CarModel { get; set; }

    public string CarYear { get; set; }

    public string CarColourway { get; set; }

    public string CarVin { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}