// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CarRentalG2.Models;

public partial class CarRentalContext : DbContext
{
    public CarRentalContext(DbContextOptions<CarRentalContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<Car> Cars { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.BookingId).HasName("PK__Bookings__73951ACD90087244");

            entity.Property(e => e.BookingId).HasColumnName("BookingID");
            entity.Property(e => e.BookingStatus)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Pending", "DF_Bookings_Status");
            entity.Property(e => e.CarId).HasColumnName("CarID");
            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.PaymentType)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Not Paid", "DF_Bookings_PaymentType");
            entity.Property(e => e.StartDate).HasColumnType("datetime");

            entity.HasOne(d => d.Car).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.CarId)
                .HasConstraintName("FK_Bookings_Cars");

            entity.HasOne(d => d.Customer).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_Bookings_Customers");
        });

        modelBuilder.Entity<Car>(entity =>
        {
            entity.HasKey(e => e.CarId).HasName("PK__Cars__68A0340EA14D11DB");

            entity.Property(e => e.CarId).HasColumnName("CarID");
            entity.Property(e => e.CarColourway)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CarMake)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CarModel)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CarVin)
                .IsRequired()
                .HasMaxLength(17)
                .HasColumnName("CarVIN");
            entity.Property(e => e.CarYear)
                .IsRequired()
                .HasMaxLength(4);
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.CustomerId).HasName("PK__Customer__A4AE64B86715060D");

            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");
            entity.Property(e => e.CustomerAddress)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.CustomerEmail)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.CustomerName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CustomerPhone)
                .IsRequired()
                .HasMaxLength(20);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}