CREATE DATABASE StudentG1;
USE StudentG1;

CREATE TABLE Modules (
	ModuleID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ModuleCode NVARCHAR(8) NOT NULL,
	ModuleName NVARCHAR(100) NOT NULL,
	ModuleCredits INT NOT NULL
);
CREATE TABLE Students (
	StudentID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	StudentName NVARCHAR(100) NOT NULL,
	StudentSurname NVARCHAR(100) NOT NULL,
	StudentDOB DATE NOT NULL
);
CREATE TABLE ModuleStudents (
	AssignmentID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ModuleID INT NOT NULL,
	StudentID INT NOT NULL,
	CONSTRAINT FK_MS_Modules FOREIGN KEY (ModuleID) REFERENCES Modules(ModuleID),
	CONSTRAINT FK_MS_Students FOREIGN KEY (StudentID) REFERENCES Students(StudentID)
);