// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DeleteConstraintExampleG2.Models;

public partial class Module
{
    public int ModuleId { get; set; }

    public string ModuleCode { get; set; }

    public string ModuleName { get; set; }

    public int ModuleCredits { get; set; }

    public virtual ICollection<ModuleStudent> ModuleStudents { get; set; } = new List<ModuleStudent>();
}