// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DeleteConstraintExampleG2.Models;

public partial class Student
{
    public int StudentId { get; set; }

    public string StudentName { get; set; }

    public string StudentSurname { get; set; }

    public DateOnly StudentDob { get; set; }

    public virtual ICollection<ModuleStudent> ModuleStudents { get; set; } = new List<ModuleStudent>();
}