// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DeleteConstraintExampleG2.Models;

public partial class StudentG2Context : DbContext
{
    public StudentG2Context(DbContextOptions<StudentG2Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Module> Modules { get; set; }

    public virtual DbSet<ModuleStudent> ModuleStudents { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Module>(entity =>
        {
            entity.HasKey(e => e.ModuleId).HasName("PK__Modules__2B747787614F2BF0");

            entity.Property(e => e.ModuleId).HasColumnName("ModuleID");
            entity.Property(e => e.ModuleCode)
                .IsRequired()
                .HasMaxLength(8);
            entity.Property(e => e.ModuleName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<ModuleStudent>(entity =>
        {
            entity.HasKey(e => e.AssignmentId).HasName("PK__ModuleSt__32499E57E3164AD1");

            entity.Property(e => e.AssignmentId).HasColumnName("AssignmentID");
            entity.Property(e => e.ModuleId).HasColumnName("ModuleID");
            entity.Property(e => e.StudentId).HasColumnName("StudentID");

            entity.HasOne(d => d.Module).WithMany(p => p.ModuleStudents)
                .HasForeignKey(d => d.ModuleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Modules_MS");

            entity.HasOne(d => d.Student).WithMany(p => p.ModuleStudents)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Students_MS");
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasKey(e => e.StudentId).HasName("PK__Students__32C52A79F75778A9");

            entity.Property(e => e.StudentId).HasColumnName("StudentID");
            entity.Property(e => e.StudentDob).HasColumnName("StudentDOB");
            entity.Property(e => e.StudentName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.StudentSurname)
                .IsRequired()
                .HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}