// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Library2G2.Models;

public partial class Book
{
    public int BookId { get; set; }

    public string BookTitle { get; set; }

    public virtual ICollection<Checkout> Checkouts { get; set; } = new List<Checkout>();
}