CREATE DATABASE StudentG2;

USE StudentG2;

CREATE TABLE Modules (
	ModuleID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ModuleCode NVARCHAR(8) NOT NULL,
	ModuleName NVARCHAR(100) NOT NULL,
	ModuleCredits INT NOT NULL
);

CREATE TABLE Students (
	StudentID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	StudentName NVARCHAR(100) NOT NULL,
	StudentSurname NVARCHAR(100) NOT NULL,
	StudentDOB DATE NOT NULL
);

CREATE TABLE ModuleStudents(
	AssignmentID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ModuleID INT NOT NULL,
	StudentID INT NOT NULL,
	CONSTRAINT FK_Modules_MS FOREIGN KEY (ModuleID) REFERENCES Modules(ModuleID),
	CONSTRAINT FK_Students_MS FOREIGN KEY (StudentID) REFERENCES Students(StudentID)
);