// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BirdWatcherG2.Models;

public partial class Spotting
{
    public int SpottingId { get; set; }

    public string BirdSeenDescription { get; set; }

    public DateTime? TimeSeen { get; set; }

    public string ImageUrl { get; set; }
}