-- CREATE DATABASE LibraryDBG1;

USE LibraryDBG1;

CREATE TABLE Books (
	BookID INT IDENTITY(1,1) PRIMARY KEY,
	Title NVARCHAR(200) NOT NULL,
	Author NVARCHAR(200) NOT NULL,
	ISBN NVARCHAR(200) NOT NULL,
	Edition INT NOT NULL,
	Pages INT NOT NULL
);

CREATE TABLE Patrons (
	PatronID INT IDENTITY(1,1) PRIMARY KEY,
	FullName NVARCHAR(200) NOT NULL,
	PhysicalAddress NVARCHAR(200) NOT NULL,
	EmailAddress NVARCHAR(200) NOT NULL,
	PhoneNumber NVARCHAR(20) NOT NULL
);

CREATE TABLE Loans (
	LoanID INT IDENTITY(1,1) PRIMARY KEY,
	BookID INT NOT NULL,
	PatronID INT NOT NULL,
	LoanDate DATETIME NOT NULL,
	ReturnDate DATETIME NOT NULL,

	CONSTRAINT FK_Loans_Books FOREIGN KEY (BookID) REFERENCES Books(BookID),
	CONSTRAINT FK_Loans_Patrons FOREIGN KEY (PatronID) REFERENCES Patrons(PatronID)
);