// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarRentalExampleG1.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public int CarId { get; set; }

    public int CustomerId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public string BookingStatus { get; set; }

    public string PaymentType { get; set; }

    public virtual Car Car { get; set; }

    public virtual Customer Customer { get; set; }
}